# Generated by Django 4.0.6 on 2022-07-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('parentezco', models.CharField(max_length=40)),
                ('nacimiento', models.DateField(max_length=40)),
            ],
        ),
    ]
