# Generated by Django 4.0.6 on 2022-07-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Familia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='nacimiento',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
